centerdoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ged.urls', namespace="ged")), 
    url(r'^login/', include('login.urls', namespace="login")), 
    url(r'^progressbarupload/', include('progressbarupload.urls')),
]

ged/urls.py
from django.conf.urls import include, url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='ged'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<pk>\d+)/livro/$', views.home_livro, name='home_livro'),
    url(r'^(?P<pk>\d+)/tipo/$', views.home_tipo, name='home_tipo'),
    url(r'^busca/$', views.home_busca, name='home_busca'),
    url(r'^tipo/new/$', views.tipo_new, name='tipo_new'),
    url(r'^tipo/list/$', views.tipo_list, name='tipo_list'),
    url(r'^tipo/(?P<pk>\d+)/edit/$', views.tipo_edit, name='tipo_edit'),
    url(r'^tipo/(?P<pk>\d+)/del/$', views.tipo_del, name='tipo_del'),    
    url(r'^empresa$', views.empresar, name='empresa'),
    url(r'^empresa_edit$', views.empresa, name='empresa_edit'),
    url(r'^livro/new/$', views.livro_new, name='livro_new'),
    url(r'^livro/list/$', views.livro_list, name='livro_list'),
    url(r'^livro/(?P<pk>\d+)/edit/$', views.livro_edit, name='livro_edit'),
    url(r'^livro/(?P<pk>\d+)/del/$', views.livro_del, name='livro_del'),
    # url(r'^pagina/new/$', views.pagina_new, name='pagina_new'),
    url(r'^pagina/list/$', views.pagina_list, name='pagina_list'),
    url(r'^pagina/(?P<pk>\d+)/edit/$', views.pagina_edit, name='pagina_edit'),
    url(r'^pagina/paginacao/$', views.paginacao, name='paginacao'),
    url(r'^pagina/(?P<pk>\d+)/edite/$', views.pagina_edit_e, name='pagina_edit_e'),
    url(r'^pagina/editp/$', views.pagina_edit_p, name='pagina_edit_p'),
    url(r'^pagina/(?P<livro_pk>\d+)/new/$', views.pagina_new, name='pagina_new_livro'),
    url(r'^pagina/(?P<tipo_pk>\d+)/new_tipo/$', views.pagina_new_tipo, name='pagina_new_tipo'),
    url(r'^pagina/(?P<pk>\d+)/del/$', views.pagina_del, name='pagina_del'),
    url(r'^backup_list/$', views.backup_list, name='backup_list'),
    url(r'^backup/$', views.backup, name='backup'),
    # url(r'^pagina/new/$', views.pagina_newj, name='pagina_new'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT)
    urlpatterns += static(settings.RESOURCES_URL, document_root=settings.RESOURCES_ROOT)

login/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name="login"
urlpatterns = [
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^list/$', views.list, name='list'),
	url(r'^user/(?P<pk>\d+)/edit/$', views.edit, name='edit'),
  url(r'^user/(?P<pk>\d+)/del/$', views.delete, name='delete'),    
]

ged/forms.py
from django import forms
from .models import Tipo, Empresa, Pagina, Documento

class TipoForm(forms.ModelForm):
	
	class Meta:
		model = Tipo
		fields = ('nome', )


class EmpresaForm(forms.ModelForm):
	class Meta:
		model = Empresa
		fields = ('cnpj', 'razao_social', 'fantasia', 'ie', 'logradouro', 'numero', 'bairro', 'estado', 'cidade', 'cep', 'telefone', 'email', 'site', )

class EmpresaFormRead(EmpresaForm):
  def __init__(self, *args, **kwargs):
    super(EmpresaForm, self).__init__(*args, **kwargs)
    instance = getattr(self, 'instance', None)
    for key in self.fields.keys():
      self.fields[key].widget.attrs['readonly'] = True

LADO_CHOICES = (
    ("1", "Frente"),
    ("2", "Verso")
)

class PaginaFormJ(forms.ModelForm):
	doc = forms.IntegerField(widget = forms.HiddenInput(), label='',  required = False)
	tipo = forms.ModelChoiceField(queryset= Tipo.objects.filter(removido=False))
	lado = forms.ChoiceField(label='Lado', choices=LADO_CHOICES, initial="1")

	class Meta:
		model = Pagina
		fields = ( 'tipo', 'texto', 'pagina', 'lado', 'arquivo', 'pagina', 'doc',)

class PaginaFormJRead(PaginaFormJ):
	def __init__(self, *args, **kwargs):
		super(PaginaFormJ, self).__init__(*args, **kwargs)
		instance = getattr(self, 'instance', None)
		for key in self.fields.keys():
			self.fields[key].widget.attrs['readonly'] = True
			self.fields[key].widget.attrs['disabled'] = True

OCR_CHOICES = (
    ("s", "Usar OCR"),
    ("n", "Não usar OCR")
)


class PaginaForm(forms.ModelForm):
	doc = forms.IntegerField(widget = forms.HiddenInput(), label='', required = False)
	tipo = forms.ModelChoiceField(queryset= Tipo.objects.filter(removido=False))
	ocr = forms.ChoiceField(label='OCR', choices=OCR_CHOICES, initial="n")
	class Meta:
		model = Pagina
		fields = ( 'tipo', 'ocr', 'arquivo', 'doc',)

LIVRO_CHOICES = (
    ("1", "Sim"),
    ("0", "Não")
)

class DocumentoForm(forms.ModelForm):
	frenteverso = forms.ChoiceField(label='Frente e Verso', choices=LIVRO_CHOICES)
	class Meta:
		model = Documento
		fields = ('capa', 'titulo', 'informacoes', 'paginas', 'ano', 'frenteverso')

ged/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Tipo, Empresa, Pagina, Documento, Backup
from .forms import TipoForm, EmpresaForm, PaginaForm, PaginaFormJ, EmpresaFormRead, DocumentoForm, PaginaFormJRead
from django.utils import timezone
import os
from os import path
import mimetypes
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse, Http404
import time
from django.core.paginator import Paginator, InvalidPage, EmptyPage
#ocr
from wand.image import Image
from PIL import Image as PI
import pyocr
import pyocr.builders
import io
import glob

from django.conf import settings
from unicodedata import normalize

#backup
from shutil import make_archive
import datetime
import json
from django.core import serializers

class Pasta:
		titulo = None
		data = None
		usuario = None
		id = None
		tipo = None
		paginas = None
		pagina = None
		livro = None

paginas_list = []

# Create your views here.
@login_required(login_url='login:login')
def home(request):
	livros = Documento.objects.filter(removido=False)
	_livros = Documento.objects.filter(removido=True)
	paginas = Pagina.objects.filter(removido=False, documento__isnull=True, tipo__isnull=True).order_by('tipo', 'documento', 'pagina', 'lado', 'pk')
	grupos = Tipo.objects.filter(removido=False)
	_grupos = Tipo.objects.filter(removido=True)
	pastas = []
	for grupo in grupos:
		p = Pasta()
		p.titulo = grupo.nome
		p.id = grupo.pk
		p.tipo = 'g'
		p.paginas = Pagina.objects.filter(removido=False, tipo=grupo.pk).count()
		pastas.append(p)	
	for grupo in _grupos:
		if Pagina.objects.filter(removido=False, tipo=grupo.pk):
			p = Pasta()
			p.titulo = grupo.nome
			p.id = grupo.pk
			p.tipo = 'g'
			p.paginas = Pagina.objects.filter(removido=False, tipo=grupo.pk).count()
			pastas.append(p)
	for livro in livros:
		p = Pasta()
		p.titulo = livro.titulo
		p.id = livro.pk
		p.tipo = 'l'
		if Pagina.objects.filter(removido=False, documento=livro.pk):
			p.paginas = Pagina.objects.filter(removido=False, documento=livro.pk).order_by('pagina').last().pagina
		pastas.append(p)
	for livro in _livros:
		if Pagina.objects.filter(removido=False, documento=livro.pk):
			p = Pasta()
			p.titulo = livro.titulo
			p.id = livro.pk
			p.tipo = 'l'
			if Pagina.objects.filter(removido=False, documento=livro.pk):
				p.paginas = Pagina.objects.filter(removido=False, documento=livro.pk).order_by('pagina').last().pagina
			pastas.append(p)
	for pagina in paginas:
		p = Pasta()
		p.titulo = pagina.tipo.nome
		p.id = pagina.pk
		p.tipo = 'p'
		p.data = pagina.date_add
		u = User.objects.get(pk=pagina.user_add)
		if pagina.documento:
			p.pagina = str(pagina.pagina)+'('+('Frente' if pagina.lado == 1 else 'Verso')+')'
		p.usuario = u.username
		pastas.append(p)
	paginator = Paginator(pastas, 12)
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	try:
		ps = paginator.page(page)
	except (EmptyPage, InvalidPage):
		ps = paginator.page(paginator.num_pages)

	titulo = "Todos os Documentos"	
	action = '/busca/'

	return render(request, 'ged/home.html', {'pastas':ps, 'titulo': titulo, 'action': action})

@login_required(login_url='login:login')
def home_busca(request):
	pastas = []
	if request.method=="POST":		
		paginas = Pagina.objects.filter(removido=False, texto__icontains=request.POST.get('txt_busca')).order_by('pagina', 'lado',  'documento', 'tipo', 'pk')
		for pagina in paginas:
			p = Pasta()
			p.titulo = pagina.tipo.nome
			p.id = pagina.pk
			p.tipo = 'p'
			p.data = pagina.date_add
			u = User.objects.get(pk=pagina.user_add)
			if pagina.documento:
				p.pagina = str(pagina.pagina)+'('+('Frente' if pagina.lado == 1 else 'Verso')+')'
			p.usuario = u.username
			pastas.append(p)
	paginator = Paginator(pastas, 12)
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	try:
		ps = paginator.page(page)
	except (EmptyPage, InvalidPage):
		ps = paginator.page(paginator.num_pages)

	tp = "Busca"
	filtro_id = None
	titulo = "Busca: \""+request.POST.get('txt_busca')+"\""
	action = '/busca/'

	return render(request, 'ged/home.html', {'pastas':ps, 'titulo': titulo, 'tp': tp, 'filtro_id': filtro_id, 'action': action})

@login_required(login_url='login:login')
def home_livro(request, pk):
	documento = Documento.objects.get(pk=pk)
	paginas = Pagina.objects.filter(removido=False, documento=pk).order_by('pagina', 'lado')
	pastas = []
	for pagina in paginas:
		p = Pasta()
		p.titulo = pagina.tipo.nome
		p.id = pagina.pk
		p.tipo = 'p'
		p.data = pagina.date_add
		u = User.objects.get(pk=pagina.user_add)
		if pagina.documento:
			p.pagina = str(pagina.pagina)+'('+('Frente' if pagina.lado == 1 else 'Verso')+')'
		p.usuario = u.username
		pastas.append(p)
	paginator = Paginator(pastas, 12)
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	try:
		ps = paginator.page(page)
	except (EmptyPage, InvalidPage):
		ps = paginator.page(paginator.num_pages)

	tp = "Livro"
	filtro_id = documento.pk
	titulo = documento.titulo	
	action = '/busca/'


	return render(request, 'ged/home.html', {'pastas':ps, 'titulo': titulo, 'tp': tp, 'filtro_id': filtro_id, 'action': action})

@login_required(login_url='login:login')
def home_tipo(request, pk):
	tipo = Tipo.objects.get(pk=pk)
	paginas = Pagina.objects.filter(removido=False, tipo=pk, documento__isnull=True).order_by('tipo', 'documento', 'pagina','lado', 'pk')
	livros = Documento.objects.all()
	pastas = []
	for livro in livros:
		if Pagina.objects.filter(removido=False, documento=livro.pk, tipo=pk):
			p = Pasta()
			p.titulo = livro.titulo
			p.id = livro.pk
			p.tipo = 'l'
			if Pagina.objects.filter(removido=False, documento=livro.pk):
				p.paginas = Pagina.objects.filter(removido=False, documento=livro.pk).order_by('pagina').last().pagina
			pastas.append(p)
	for pagina in paginas:
		p = Pasta()
		p.titulo = pagina.tipo.nome
		p.id = pagina.pk
		p.tipo = 'p'
		p.data = pagina.date_add
		u = User.objects.get(pk=pagina.user_add)
		if pagina.documento:
			p.pagina = str(pagina.pagina)+'('+('Frente' if pagina.lado == 1 else 'Verso')+')'
		p.usuario = u.username
		pastas.append(p)
	paginator = Paginator(pastas, 12)
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	try:
		ps = paginator.page(page)
	except (EmptyPage, InvalidPage):
		ps = paginator.page(paginator.num_pages)

	tp = "Tipo de Documento"
	filtro_id = tipo.pk
	titulo = tipo.nome	
	action = '/busca/'


	return render(request, 'ged/home.html', {'pastas':ps, 'titulo': titulo, 'tp': tp, 'filtro_id': filtro_id, 'action': action})

@login_required(login_url='login:login')
def tipo_new(request):
	if request.method=="POST":
		form = TipoForm(request.POST)
		if form.is_valid():
			tipo = form.save(commit=False)
			tipo.user_add = request.user.pk
			tipo.date_add = timezone.now()
			tipo.pasta = tipopasta(tipo.nome)
			tipo.save()
			return redirect('ged:tipo_list')
	else:
		form = TipoForm()
	return render(request, 'ged/tipo_form.html', {'form': form})

@login_required(login_url='login:login')
def tipo_edit(request, pk):
	tipo = get_object_or_404(Tipo, pk=pk)
	if request.method=="POST":
		form = TipoForm(request.POST, instance=tipo)
		if form.is_valid():
			tipo = form.save(commit=False)
			tipo.user_up = request.user.pk
			tipo.date_up = timezone.now()
			tipo.save()
			return redirect('ged:tipo_list')
	else:
		form = TipoForm(instance=tipo)
	return render(request, 'ged/tipo_form.html', {'form': form})

@login_required(login_url='login:login')
def tipo_list(request):
	grupos = Tipo.objects.filter(removido=False).order_by('nome')
	paginator = Paginator(grupos, 12)
	try:
		page = int(request.GET.get('page', '1'))
	except ValueError:
		page = 1

	try:
		gps = paginator.page(page)
	except (EmptyPage, InvalidPage):
		gps = paginator.page(paginator.num_pages)
	return render(request, 'ged/tipo_list.html', {'grupos': gps})

@login_required(login_url='login:login')
def tipo_del(request, pk):
	tipo = get_object_or_404(Tipo, pk=pk)
	tipo.removido = True
	tipo.user_del = request.user.pk
	tipo.date_del = timezone.now()
	tipo.save()
	return redirect('ged:tipo_list')

@login_required(login_url='login:login')
def livro_del(request, pk):
	livro = get_object_or_404(Documento, pk=pk)
	livro.removido = True
	livro.user_del = request.user.pk
	livro.date_del = timezone.now()
	livro.save()
	return redirect('ged:livro_list')

@login_required(login_url='login:login')
def pagina_del(request, pk):
	pagina = get_object_or_404(Pagina, pk=pk)
	pagina.removido = True
	pagina.user_del = request.user.pk
	pagina.date_del = timezone.now()
	pagina.save()
	if pagina.documento:
		return redirect(reverse('ged:home_livro', kwargs={ 'pk': pagina.documento.pk }))
	else:
		return redirect(reverse('ged:home_tipo', kwargs={ 'pk': pagina.tipo.pk }))


	# empresa
@login_required(login_url='login:login')
def empresa_new(request):
	if request.method=="POST":
		form = EmpresaForm(request.POST)
		if form.is_valid():
			empresa = form.save(commit=False)
			empresa.user_add = request.user.pk
			empresa.date_add = timezone.now()
			empresa.save()
			return redirect('ged:empresa_edit')
	else:
		form = EmpresaForm()
	return render(request, 'ged/empresa.html', {'form': form})

@login_required(login_url='login:login')
def empresa(request):
	empresa = Empresa.objects.all().first()
	if request.method=="POST":
		if empresa:
			form = EmpresaForm(request.POST, instance=empresa)
			if form.is_valid():
				empresa = form.save(commit=False)
				empresa.user_up = request.user.pk
				empresa.date_up = timezone.now()
				empresa.save()
				return redirect('ged:empresa')
		else:
			form = EmpresaForm(request.POST)
			if form.is_valid():
				empresa = form.save(commit=False)
				empresa.user_add = request.user.pk
				empresa.date_add = timezone.now()

ged/templates/ged/home.html
{% extends 'ged/base.html' %}

{% block content %}
  <div class="container ">
    <form class="form-inline my-2 my-lg-0" action="{{action}}" method="POST">
      {% csrf_token %}
        <input class="form-control mr-sm-2 col-md-8" type="text" id="txt_busca" name="txt_busca" placeholder="Busca">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
{% if pastas %}
<div class="col-12 col-md-9">
  {% if tp  or filtros %}
    <div id="filtros_busca">
      Filtro: <span class="badge badge-pill badge-info">{{tp}}</span>
    </div>
  {% endif %}
  <div class="row" >
    <div class="col-md-9">
      <h3 class="my-2">{{titulo}}</h3>
    </div>
    <div class="col-md-3 my-2" >
      {% if tp  or filtros %}
      <a class="btn btn-info" href="{% url 'ged:home' %}">Voltar</a>      
      {% endif %}
      <ul class="pagination" style="float: right;">
        {% if pastas.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ pastas.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Anterior</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item page-link">
          {{ pastas.number }}  de {{ pastas.paginator.num_pages }}
        </li>
        {% if pastas.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ pastas.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Próxima</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="row">
    {% for pasta in pastas.object_list %}
    <div class="col-lg-2 col-sm-6 portfolio-item">
      <div class="card h-100">
        {% if pasta.tipo == 'l'%}
          <a href="{% url 'ged:home_livro' pk=pasta.id %}" >
            <img class="card-img-top" src="/media/image/livros.png" alt="">
            <div class="card-body">
              <h4 class="card-title small">
                  {{pasta.titulo}}
              </h4>
              {% if pasta.paginas %}
                <small>Pags:{{pasta.paginas}}</small>
              {% endif %}
            </div>
          </a>
        {% endif %}
        {% if pasta.tipo == 'g'%}
          <a href="{% url 'ged:home_tipo' pk=pasta.id %}" >
            <img class="card-img-top" src="/media/image/grupo.png" alt="">
            <div class="card-body">
              <h4 class="card-title small">
                  {{pasta.titulo}}
              </h4>
              {% if pasta.paginas %}
                <small>Qtds:{{pasta.paginas}}</small>
              {% endif %}
            </div>
          </a>
        {% endif %}
        {% if pasta.tipo == 'p'%}
          <a href="{% url 'ged:pagina_edit' pk=pasta.id %}" >
            <img class="card-img-top" src="/media/image/pagina.png" alt="">
            <div class="card-body">
              <h4 class="card-title small">
                  {{pasta.titulo}}
              </h4>
          </a>
              <p class="card-text small text-right">
                {{pasta.usuario}}
                {{pasta.data|date:"d/m/Y" }}
                <small>Pag:{{pasta.pagina}}</small>
              </p>
            </div>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- /.row -->
  <!-- Pagination -->
  <ul class="pagination justify-content-center">
    {% if pastas.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ pastas.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Anterior</span>
      </a>
    </li>
    {% endif %}
    <li class="page-item page-link">
      {{ pastas.number }}  de {{ pastas.paginator.num_pages }}
    </li>
    {% if pastas.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ pastas.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Próxima</span>
        </a>
      </li>
    {% endif %}
  </ul>
</div>
{% else %}
<div class="col-12 col-md-9">
  <div class="row" >
    <div class="col-md-9">
      <h3 class="my-2">{{titulo}}</h3>
      <p>Não há registros</p>
    </div>  
  </div>
</div>

{% endif %}

<div class="col-12 col-md-3" id="sidebar">
      {% if tp == "Livro" %}
        <a class="btn btn-primary btn-lg btn-block btn-home" href="{% url 'ged:pagina_new_livro' livro_pk=filtro_id %}">Adicionar ao {{titulo}}</a>
      {% endif %}
      {% if tp == "Tipo de Documento" %}
        <a class="btn btn-primary btn-lg btn-block btn-home" href="{% url 'ged:pagina_new_tipo' tipo_pk=filtro_id %}">Adicionar ao {{titulo}}</a>
      {% endif %}
    <a href="{% url 'ged:livro_new' %}" class="btn btn-primary btn-lg btn-block btn-home">Novo Livro</a>
    <a href="{% url 'ged:pagina_new_livro' livro_pk=0 %}" class="btn btn-primary btn-lg btn-block btn-home">Novo Documento</a>
</div>

 <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Buscando ...</h4>
        </div>
        <div class="modal-body">
          <div class="prog">
            <div class="prog" style="width: 100%;text-align: center;" >
              <div id="im_result">
                <img src="/media/image/progresso.gif">
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

ged/templates/ged/pagina_form.html
{% extends 'ged/base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}
<div class="col-12 col-md-6">
  {% if livro %}
    {% if not proximo %}
      <a class="btn btn-primary" href="{% url 'ged:pagina_new_livro' livro_pk=livro.pk %}">Adicionar</a>
    {% endif %}

  {% else %}
    {% if form.instance.tipo %}
      <a class="btn btn-primary" href="{% url 'ged:pagina_new_tipo' tipo_pk=form.instance.tipo.pk %}">Adicionar</a>
    {% endif %}
  {% endif %}
<h3 class="my-4">Documentos
  <small><span class="badge badge-secondary ud_bt" data-toggle="tooltip" data-placement="top" 
    {% if infor_livro %}
    title="Frente e Verso: {{infor_livro.tipo_livro}} | Últ. Pág.: {{infor_livro.ultima}}({{infor_livro.lado_livro}})">
    {% endif %}
    {{livro.titulo}}</span></small>
</h3>
  {% if form.instance.id %}
    <input id="pagina_id" value="{{form.instance.id}}" type="hidden" />
  {% endif %}
  {% if livro %}
    <input id="livro_id" value="{{livro.pk}}" type="hidden" />
  {% endif %}
<form method="POST" action='{{ action }}' enctype="multipart/form-data" id="form_pagina">{% csrf_token %}
	{% for field in form %}
    {% if field.errors %}
      <div class="form-group">
        <label for="id_{{ field.name }}" class="col-form-label">{{ field.label }}</label>
        {{ field|add_class:"form-control"}}
        <span></span>
        <div>
          {% for error in field.errors %}{{ error }}{% endfor %}
        </div>
      </div>
    {% else %}
      <div class="form-group">
        <label for="id_{{ field.name }}" class="col-form-label">{{ field.label }}</label>
        {% if field.name == 'pagina' or field.name == 'lado'%}
        {{ field|add_class:"form-control check_pagina" }}
        {% else %}
        {{ field|add_class:"form-control" }}
        {% endif %}
        {% if field.help_text %}
          <div>{{ field.help_text }}</div>
        {% endif %}
      </div>
    {% endif %}
  {% endfor %}
  {% if editar or not form.instance.texto %}
    <button type="submit" class="btn btn-primary">Salvar</button>
  {% else %}
    {% if form.instance.id %}
      <a class="btn btn-primary" href="{% url 'ged:pagina_edit_e' pk=form.instance.id %}">Editar</a>
    {% endif %}
  {% endif %}
  {% if livro %}
  <a class="btn btn-info" href="{% url 'ged:home_livro' pk=livro.pk %}">Voltar</a>
  {% endif %}
  {% if not livro %}
    {% if form.instance.tipo %}
      <a class="btn btn-info" href="{% url 'ged:home_tipo' pk=form.instance.tipo.pk %}">Voltar</a>
    {% else %}
      <a class="btn btn-info" href="{% url 'ged:home' %}">Voltar</a>
    {% endif %}
  {% endif %}
  {% if form.instance.id %}
  <a class="btn btn-danger confirm-remove" href="{% url 'ged:pagina_del' pk=form.instance.id %}">Apagar</a>
  {% endif %}

</form>
 <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Enviando ...</h4>
        </div>
        <div class="modal-body">
          <div class="prog">
            <div class="prog" style="width: 100%;text-align: center;" >
              <div class="alert alert-success" style="display:none;">
                <strong>Sucesso!</strong> Operação realizada com sucesso.
              </div>
              <div class="alert alert-danger" style="display:none;">
                <strong>Desculpe!</strong> Não foi possível realizar operação.
              </div>
              <div id="im_result">
                <img src="/media/image/progresso.gif">
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
</div>
</div>

<div class="col-12 col-md-6">
  <div>
    {% if form.instance.id %}
      {% if anterior %}
        <a style="float: left;" id="bt_ant" class="btn btn-info pull-right" href="{% url 'ged:pagina_edit_p' %}" alt="{{form.instance.id}}||{{livro}}" >Anterior</a>
      {% endif %}
      {% if proximo %}
        <a style="float: right;" id="bt_pro" class="btn btn-info pull-right" href="{% url 'ged:pagina_edit_p' %}" alt="{{form.instance.id}}||{{livro}}" >Proximo</a>
      {% endif %}
    {% endif %}
  </div>
  <div>
    <embed src="{{arquivo}}" width= "100%" height= "450">
  </div>
</div>
{% endblock content %}
{% block javascript %}
  <script src="{% static 'ged/bootstrap/js/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'ged/bootstrap/js/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'ged/bootstrap/js/jquery.fileupload.js' %}"></script>

{% endblock %}