centerdoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('ged.urls', namespace="ged")), 
    url(r'^login/', include('login.urls', namespace="login")), 
    url(r'^progressbarupload/', include('progressbarupload.urls')),
]

ged/urls.py
from django.conf.urls import include, url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='ged'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<pk>\d+)/livro/$', views.home_livro, name='home_livro'),
    url(r'^(?P<pk>\d+)/tipo/$', views.home_tipo, name='home_tipo'),
    url(r'^busca/$', views.home_busca, name='home_busca'),
    url(r'^tipo/new/$', views.tipo_new, name='tipo_new'),
    url(r'^tipo/list/$', views.tipo_list, name='tipo_list'),
    url(r'^tipo/(?P<pk>\d+)/edit/$', views.tipo_edit, name='tipo_edit'),
    url(r'^tipo/(?P<pk>\d+)/del/$', views.tipo_del, name='tipo_del'),    
    url(r'^empresa$', views.empresar, name='empresa'),
    url(r'^empresa_edit$', views.empresa, name='empresa_edit'),
    url(r'^livro/new/$', views.livro_new, name='livro_new'),
    url(r'^livro/list/$', views.livro_list, name='livro_list'),
    url(r'^livro/(?P<pk>\d+)/edit/$', views.livro_edit, name='livro_edit'),
    url(r'^livro/(?P<pk>\d+)/del/$', views.livro_del, name='livro_del'),
    # url(r'^pagina/new/$', views.pagina_new, name='pagina_new'),
    url(r'^pagina/list/$', views.pagina_list, name='pagina_list'),
    url(r'^pagina/(?P<pk>\d+)/edit/$', views.pagina_edit, name='pagina_edit'),
    url(r'^pagina/paginacao/$', views.paginacao, name='paginacao'),
    url(r'^pagina/(?P<pk>\d+)/edite/$', views.pagina_edit_e, name='pagina_edit_e'),
    url(r'^pagina/editp/$', views.pagina_edit_p, name='pagina_edit_p'),
    url(r'^pagina/(?P<livro_pk>\d+)/new/$', views.pagina_new, name='pagina_new_livro'),
    url(r'^pagina/(?P<tipo_pk>\d+)/new_tipo/$', views.pagina_new_tipo, name='pagina_new_tipo'),
    url(r'^pagina/(?P<pk>\d+)/del/$', views.pagina_del, name='pagina_del'),
    url(r'^backup_list/$', views.backup_list, name='backup_list'),
    url(r'^backup/$', views.backup, name='backup'),
    # url(r'^pagina/new/$', views.pagina_newj, name='pagina_new'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT)
    urlpatterns += static(settings.RESOURCES_URL, document_root=settings.RESOURCES_ROOT)

login/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name="login"
urlpatterns = [
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^list/$', views.list, name='list'),
	url(r'^user/(?P<pk>\d+)/edit/$', views.edit, name='edit'),
  url(r'^user/(?P<pk>\d+)/del/$', views.delete, name='delete'),    
]

login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Nome')
    last_name = forms.CharField(max_length=30, required=True, label='Sobrenome')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )

login/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.contrib.auth.views import login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from .forms import SignUpForm

def logout(request, *args, **kwargs):
	kwargs['next_page'] = 'login:login'
	return auth_logout(request, *args, **kwargs)
	
def login(request, *args, **kwargs):
	if request.user.is_authenticated():
		return redirect('ged:home')
	kwargs['extra_context'] = {'next':'/'}
	kwargs['template_name'] = 'login/login.html'
	return auth_login(request, *args, **kwargs)

def signup(request):
	if request.method=='POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('login:list')
	else:
			form = SignUpForm()
	return render(request, 'login/user_form.html', {'form': form})

def list(request):
	users = User.objects.filter(is_active=True)
	return render(request, 'login/user_list.html', {'users': users})

def edit(request, pk):
	user = User.objects.get(pk=pk)
	if request.method=='POST':
		form = SignUpForm(request.POST, instance=user)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return redirect('login:list')
	else:
			form = SignUpForm(instance=user)
	return render(request, 'login/user_form.html', {'form': form})

def delete(request, pk):
	user = User.objects.get(pk=pk)
	user.is_active = False
	user.save()
	return redirect('login:list')

login/templates/login/home.html
<div class='row'>
	<div class="col-md-12 sidenav login">
		<div class="col-md-2 logo">
			<img src="{% static 'imagens/runze.jpg' %}">
		</div>
		<div class="col-md-10">
		<form method='POST' class='login' action=" {{ request.path }}{% if next %}?next={{ next }}{% endif %} ">{% csrf_token %}
		{% for field in form %}
		<fieldset class="control-group">
		    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
		    <div class="controls">
		        {{ field }}
		        <p class="help-text">{{ field.help_text }} </p>
		    </div>
		</fieldset>
		{% endfor %}
		<div class="input-group">
			<span class="input-group-btn">
				<button class="btn btn-success" type="submit">
					Logar
				</button>
			</span>
		</div>
	</div>
	</form>
	</div>
</div>

login/templates/login/login.html
{% extends 'ged/base.html' %}
{% load staticfiles %}

{% block content %}
<div class='row'>
	<div class="col-md-12 sidenav login">
		<div class="col-md-10">
		<form method='POST' class='login' action=" {{ request.path }}{% if next %}?next={{ next }}{% endif %} ">{% csrf_token %}
		{% for field in form %}
		<fieldset class="control-group">
		    <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
		    <div class="controls">
		        {{ field }}
		        <p class="help-text">{{ field.help_text }} </p>
		    </div>
		</fieldset>
		{% endfor %}
		<div class="input-group">
			<span class="input-group-btn">
				<button class="btn btn-success" type="submit">
					Logar
				</button>
			</span>
		</div>
	</div>
	</form>
	</div>
</div>
{% endblock content %}

login/templates/login/logout.html
<script>
document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/";
location.href="/login/";
</script>

login/templates/login/user_form.html
{% extends 'ged/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="col-12 col-md-8">
<h3 class="my-4">Usuário</h3>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
<!--         {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %} -->
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</div>
{% endblock content %}

login/templates/login/user_list.html
{% extends 'ged/base.html' %}
{% block content %}

<div class="col-12 col-md-8">
<h3 class="my-4">Usuários
  <small><a class="btn btn-secondary ud_bt" href="{% url 'login:signup' %}">Adicionar</a></small>
</h3>
	<div class="panel list-group">
 		{% for usuario in users %}	
 		<span class="list-group-item">
 			{{ usuario.get_full_name }} ({{usuario.username}})
			<span class="ud_bt">
				<a href="{% url 'login:edit' pk=usuario.pk %}"><span class="glyphicon glyphicon-edit pull-right"></span></a>
				<a class="confirm-remove" href="{% url 'login:delete' pk=usuario.pk %}"><span class="glyphicon glyphicon-trash pull-right"></span></a>
			</span>
 		</span>
		{% endfor %}
  </div>
</div>
{% endblock content %}